version: 2.1

orbs:
  win: circleci/windows@4.1.1 # The Windows orb gives you everything you need to start using the Windows executor

jobs:
  test:
    description: Setup and run application tests
    executor:
      name: win/server-2022
    steps:
      - checkout

# VS Code Extension Version: 1.4.0
workflows:
  test:
    jobs:
      - test