version: 2.1

orbs:
  win: circleci/windows@4.1.1 # The Windows orb gives you everything you need to start using the Windows executor
  general-platform-helpers: okta/general-platform-helpers@1.9
  python: circleci/python@2.0.3
  aws-cli: circleci/aws-cli@5.1

jobs:
  reversing-labs:
    steps:
      - checkout
  
      - run: dotnet --version

      - run: 
          name: build okta-hosted-login v3 to scan
          command: dotnet build ./samples-aspnetcore-3x/okta-hosted-login/okta-aspnetcore-mvc-example.sln
       
      - run: 
          name: build resource-server v3 to scan
          command: dotnet build ./samples-aspnetcore-3x/resource-server/okta-aspnetcore-webapi-example.sln 

      - run: 
          name: build self-hosted-login v3 to scan
          command: dotnet build ./samples-aspnetcore-3x/self-hosted-login/okta-aspnetcore-mvc-example.sln

      - run: 
          name: build social-login v3 to scan
          command: dotnet build ./samples-aspnetcore-3x/social-login/okta-aspnetcore-mvc-example.sln
     
      - run: 
          name: build resource-server v6 to scan
          command: dotnet build ./samples-aspnetcore-6x/resource-server/okta-aspnetcore-webapi-example.sln 
  
      - run: 
          name: build self-hosted-login v6 to scan
          command: dotnet build ./samples-aspnetcore-6x/self-hosted-login/okta-aspnetcore-mvc-example.sln

      - run: 
          name: build okta-hosted-login v7 to scan
          command: dotnet build ./samples-aspnetcore-7x/okta-hosted-login/okta-aspnetcore-razorpages-example/okta-aspnetcore-razorpages-example.sln
        
      - run: 
          name: build self-hosted-login v7 to scan
          command: dotnet build ./samples-aspnetcore-7x/self-hosted-login/okta-aspnetcore-razorpages-example/okta-aspnetcore-razorpages-example.sln
          
      // Necessary to Install rl wrapper   
      - run:
          name: Install Python
          command: |
            sudo apt-get update
            sudo apt-get install -y python3 python3-pip
            sudo pip install --upgrade pip
  
      // Download the scanner from Okta Security
      - run:
          name: Download Reverse Labs Scanner
          command: |
            curl https://dso-resources.oktasecurity.com/scanner \
              -H "x-api-key: $RESOURCE_TOKEN" \
              --output rl_wrapper-0.0.2+35ababa-py3-none-any.whl
      // Install the wrapper that was downloaded
      - run:
          name: Install RL Wrapper
          command: |
            pip install ./rl_wrapper-0.0.2+35ababa-py3-none-any.whl
  
      // Setup the AWS profile
      - aws-cli/setup:
          profile_name: default
          role_arn: $AWS_ARN
          region: us-east-1
  
      // Get the credentials and save to env
      - run: >-
          eval "$(aws configure export-credentials --profile default --format env)" 2> /dev/null
  
      // Run the wrapper, do not change anything here
      - run:
          name: Run Reversing Labs Wrapper Scanner
          command: |
            rl-wrapper \
              --artifact ${CIRCLE_WORKING_DIRECTORY/#\~/$HOME} \
              --name $CIRCLE_PROJECT_REPONAME\
              --version $CIRCLE_SHA1\
              --repository $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME \
              --commit $CIRCLE_SHA1 \
              --build-env "circleci" \
              --suppress_output

  test:
    description: Setup and run application tests
    executor:
      name: win/server-2022
    steps:
      - checkout

# VS Code Extension Version: 1.4.0
workflows:
  "Malware Scanner":
    jobs:
      - reversing-labs:
          context:
            - static-analysis
  test:
    jobs:
      - test
  # See OKTA-624801
  semgrep:
    jobs:
      - general-platform-helpers/job-semgrep-scan:
          name: "Scan with Semgrep"
          context:
            - static-analysis
